In [4]:
import numpy as np
import pandas as pd

# Load data 

In [13]:
#def get_data():
df = pd.read_csv('ecommerce_data.csv')
# get sample data
X = df.drop('user_action', axis = 1)
# get target sample data
Y = df['user_action']
Y.head() 

array([0, 1, 0, 2, 2, 2, 0, 0, 1, 0, 3, 0, 0, 1, 0, 3, 1, 1, 1, 0, 2, 0, 0,
       3, 0, 1, 0, 0, 2, 2, 0, 1, 2, 2, 1, 0, 0, 1, 1, 0, 2, 1, 0, 1, 3, 0,
       1, 0, 0, 1, 2, 3, 1, 2, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 3, 0, 2,
       1, 1, 3, 1, 0, 3, 0, 2, 0, 2, 0, 1, 0, 1, 0, 0, 1, 0, 2, 3, 1, 0, 0,
       1, 0, 0, 1, 0, 2, 0, 1, 0, 1, 1, 2, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 2,
       2, 0, 0, 2, 0, 0, 0, 1, 2, 1, 2, 0, 2, 2, 0, 2, 2, 0, 0, 0, 3, 1, 1,
       1, 0, 0, 1, 1, 0, 2, 0, 0, 0, 0, 0, 2, 0, 1, 0, 1, 0, 0, 0, 2, 0, 1,
       0, 2, 1, 1, 0, 1, 2, 0, 0, 0, 0, 3, 0, 1, 0, 0, 0, 0, 1, 0, 3, 0, 2,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 3, 3, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 2, 0, 0, 1, 2, 0, 2, 0, 0, 1, 3, 1, 2,
       0, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 3, 0, 0, 1, 0, 2, 2, 1, 0, 2,
       0, 0, 3, 2, 1, 0, 3, 0, 0, 1, 0, 2, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 0,

# Preprocessing

In [3]:
# normalize column n_products_viewed and visit_duration
cols_to_norm = ['n_products_viewed','visit_duration']
X[cols_to_norm] = X[cols_to_norm].apply(lambda x: (x - x.mean()) / x.std())

X.head()

is_mobile  n_products_viewed  visit_duration  is_returning_visitor  \
0          1          -0.816161       -0.407869                     0   
1          1           0.139531       -0.498929                     0   
2          1          -0.816161       -1.037804                     1   
3          1           0.139531        0.618313                     1   
4          0           0.139531        0.981728                     1   

   time_of_day  
0            3  
1            2  
2            1  
3            1  
4            1

In [4]:
# One-Hot encoding for categorical column time_of_day
one_hot = pd.get_dummies(X['time_of_day'], prefix = 'time_of_day')
X.drop('time_of_day', axis=1, inplace=True)
X = X.join(one_hot)
X.head()

is_mobile  n_products_viewed  visit_duration  is_returning_visitor  \
0          1          -0.816161       -0.407869                     0   
1          1           0.139531       -0.498929                     0   
2          1          -0.816161       -1.037804                     1   
3          1           0.139531        0.618313                     1   
4          0           0.139531        0.981728                     1   

   time_of_day_0  time_of_day_1  time_of_day_2  time_of_day_3  
0            0.0            0.0            0.0            1.0  
1            0.0            0.0            1.0            0.0  
2            0.0            1.0            0.0            0.0  
3            0.0            1.0            0.0            0.0  
4            0.0            1.0            0.0            0.0

## Wrapping it as a function

In [28]:
def get_data():
    df = pd.read_csv('ecommerce_data.csv')
    # get sample data
    X = df.drop('user_action', axis = 1)
    # get target sample data
    Y = df['user_action']

    # normalize column n_products_viewed and visit_duration
    cols_to_norm = ['n_products_viewed','visit_duration']
    X[cols_to_norm] = X[cols_to_norm].apply(lambda x: (x - x.mean()) / x.std())

    # One-Hot encoding for categorical column time_of_day
    one_hot = pd.get_dummies(X['time_of_day'], prefix = 'time_of_day')
    X.drop('time_of_day', axis=1, inplace=True)
    X = X.join(one_hot)
    
    return X, Y

    

## Get only binary data for logistic regression training

In [29]:
# get only binary data for logistic regression training
#def get_binary_data():
X, Y = get_data()
Y.describe()

count    500.00000
mean       0.74800
std        0.89336
min        0.00000
25%        0.00000
50%        0.00000
75%        1.00000
max        3.00000
Name: user_action, dtype: float64

In [30]:
X2 = X[Y<=1]
Y2 = Y[Y<=1]
Y2.describe() 

count    398.000000
mean       0.364322
std        0.481845
min        0.000000
25%        0.000000
50%        0.000000
75%        1.000000
max        1.000000
Name: user_action, dtype: float64

## ...as a funtion

In [31]:
def get_binary_data():
    X, Y = get_data()
    X2 = X[Y<=1]
    Y2 = Y[Y<=1]
    
    return X2, Y2 

# Making prediction

In [55]:
X, Y =  get_data()
X = X.as_matrix()
Y = Y.as_matrix()

# randomly initialize weights

# no. hidden units
M = 5 

# no. features
D = X.shape[1] 

# no. unique values on Y
K = len(set(Y))

# layer 1 weights and bias
W1 = np.random.randn(D, M) 
b1 = np.zeros(M)
# layer 2 weights and bias
W2 = np.random.randn(M, K)
b2 = np.zeros(K)



Softmax 
$$f_j(z) = \frac{e^{z_j}}{\sum_k e^{z_k}}$$

Forward propagation
$$f(x_i, W, b) =  W x_i + b$$

In [56]:
def softmax(a):
    expA = np.exp(a)
    return expA / expA.sum(axis=1, keepdims=True)

# Predicting probability based on initialized weights
def forward(X, W1, b1, W2, b2):
    # activation function
    Z = np.tanh(X.dot(W1)+b1)
    return softmax(Z.dot(W2)+b2)

# calculate probability for each class
P_Y_given_X = forward(X, W1, b1, W2, b2) 
print(P_Y_given_X)

# pick highest probability
predictions = np.argmax( P_Y_given_X, axis=1)
print(predictions)

# calculate the accuracy
def classification_rate(Y, P):
    return np.mean(Y == P)

print( "Score:", classification_rate(Y, predictions))

[[ 0.53689694  0.05554514  0.00476827  0.40278964]
 [ 0.13867359  0.13753007  0.67136608  0.05243027]
 [ 0.3383697   0.2840337   0.30957083  0.06802577]
 ..., 
 [ 0.52758605  0.09027827  0.03015522  0.35198046]
 [ 0.5726278   0.06936453  0.00234873  0.35565894]
 [ 0.00203329  0.00410359  0.84992726  0.14393585]]
[0 2 0 2 2 2 2 0 2 0 2 0 0 3 0 2 2 2 2 0 2 0 0 2 0 0 2 3 2 2 0 2 2 2 2 0 0
 2 3 2 2 2 0 2 2 2 2 2 2 2 2 2 3 2 2 2 2 3 2 2 0 3 3 0 2 3 2 3 2 3 2 0 2 2
 0 3 2 2 0 2 2 2 0 0 3 2 2 2 2 2 0 2 3 2 2 2 2 2 0 2 2 2 0 2 0 2 2 2 2 0 2
 2 0 0 2 2 0 2 3 0 2 2 2 3 3 3 2 0 2 2 0 0 2 0 3 2 2 2 2 2 3 3 2 2 2 2 2 0
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 2 2 2 3 2 2 2 2 2 2 2 0 2 2 2 0 2
 2 2 2 0 0 2 3 1 2 0 2 3 2 2 0 2 2 2 2 2 2 2 3 3 2 2 3 2 3 0 2 0 3 2 2 2 2
 0 2 3 0 3 2 3 3 2 0 3 0 0 2 0 2 2 2 2 2 2 3 2 0 2 0 2 2 2 0 2 1 2 0 3 2 3
 0 2 3 2 2 2 0 2 2 2 2 2 2 2 2 2 2 3 2 2 2 3 2 2 0 0 2 2 2 2 3 2 2 2 2 2 0
 2 0 3 2 0 2 3 3 2 2 2 3 2 2 2 2 2 0 2 3 2 2 2 2 3 2 0 0 3 3 2 2 2 0 3 2 2
 2 2 2 3 0 